version: "3.0"

services:
  application:
    build: ./
    image: backend
    command: yarn start
    depends_on:
      - database
    networks:
      dev:
        aliases:
          - app.dev
    ports:
    - 3000:3000
    volumes:
    - ./:/home/backend
  database:
    image: postgres
    networks:
      dev:
        aliases:
          - db.dev
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=1234
networks:
  dev:
    external:
      name: dev